# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.36.1"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    ensure_git_status_clean
    increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :deploy do
    # snapshot
    version = version_bump_podspec(path: "Stormcloud.podspec", bump_type: "patch")
    add_git_tag(
 	 tag: version,
	)
	git_commit(path: ["./Stormcloud/Info.plist", "./Stormcloud.xcodeproj/project.pbxproj", "StormcloudTests/Info.plist", "Stormcloud.podspec"], message: "Version Bump")
	push_to_git_remote
	
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    notification(subtitle: "Stormcloud processing finished", message: "Completed '#{lane}' successfully")
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
